<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitwardenManager.Core\BitwardenManager.Core.csproj" />
    <ProjectReference Include="..\BitwardenManager.ApiClient\BitwardenManager.ApiClient.csproj" />
    <ProjectReference Include="..\BitwardenManager.CliWrapper\BitwardenManager.CliWrapper.csproj" />
  </ItemGroup>

</Project>
